version: '3.2'

networks:
  NETWORK:

services:
  grafana:
    image: grafana/grafana
    environment:
     - GF_DATABASE_TYPE=mysql
     - GF_DATABASE_HOST=database
     - GF_DATABASE_USER=root
     - GF_DATABASE_PASSWORD=inet123456
     - GF_DATABASE_NAME=test_db
     - GF_SESSION_PROVIDER=mysql
     - GF_SESSION_PROVIDER_CONFIG=test:inet123456@tcp(database:3306)/test_db
    ports:
     - "3200:3000"
    networks:
      - NETWORK
    deploy:
     restart_policy:
        condition: on-failure
     replicas: 5

  database:
    image: mariadb:10
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=inet123456
      - MYSQL_DATABASE=test_db
    networks:
      - NETWORK