version: '3.2'

networks:
  NETWORK:
  
services:
  grafana:
    image: grafana/grafana
    ports:
     - "3000:3000"
    networks:
      - NETWORK
    deploy:
     restart_policy:
        condition: on-failure
     replicas: 5